### ISSUE TITLE
Problems with firefox

### ISSUE THREAD

**Issue by Casal0x** [bitmap/react-hook-inview#12]
I tested in firefox dunno why the inview stay in true with the component out of the viewport also tried with onEnter and onLeave, the onLeave is not being executed in firefox.

const [componentId, setComponentId] = useState(null);
  const [ref, inView] = useInView({
    threshold: 0.7,
  });

  useLayoutEffect(() => {
    effectCallback && effectCallback(inView);
    inView && setLoaded(true);
  }, [inView, effectCallback]);

  return (
    <div
      id={stickyNavId}
      className={`${className}${
        inView && componentId === stickyNavId ? " ns-inview" : ""
      }`}
      data-id={componentID}
      style={style}
      ref={ref}
    >
      {(loaded || inView) && children}
    `</div>`
  );
};

**Comment by bitmap** [comment]
Hey @Casal0x, thanks for bringing this to my attention.

For posterity, this is actually a bug with other browser's implementation of IntersectionObserver. Firefox is exhibiting the _correct_ behavior.

https://bugs.chromium.org/p/chromium/issues/detail?id=925643

I updated the package to address this, if you install `react-hook-inview@4.20` you should see the intended effect across all browsers.

Thanks again!
