### ISSUE TITLE
unobserveOnEnter doesn't seem to be working

### ISSUE THREAD

**Issue by bogdancss** [bitmap/react-hook-inview#16]
Hey, trying to use the `unobserveOnEnter`, but it does not seem to be working.

Here's what I am using:

```
const [ref, inView] = useInView({ unobserveOnEnter: true })
console.log(inView)
```

but this flips between true and false as I scroll past the item.

**Comment by bitmap** [comment]
Hello, I can't seem to reproduce this issue locally, and tests for this feature aren't failing. Can you provide me with a little more info?

- Browser version
- Your package version (latest is 4.3.1)
- If possible, link to a sandbox or repository that reproduces this behavior

Thanks
