### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by nitz-iron** [bitmap/react-hook-inview#25]
Hi, thanks for the great library.
the library only supports: react@"^16.8.0 || ^17.0.0" 

pls also support 18 
thanks.

**Comment by kupe517** [comment]
Any update on if / when support for React v18 will be coming?

**Comment by bitmap** [comment]
`v4.5.0` has support for React 18: https://www.npmjs.com/package/react-hook-inview/v/4.5.0

Thanks for your patience.
