### ISSUE TITLE
"Syntax Error" in IE11

### ISSUE THREAD

**Issue by uxigene** [bitmap/react-hook-inview#9]
The hook does not work in IE11. It throws "Syntax Error" at "./node_modules/react-hook-inview/dist/esm/index.js"

**Comment by bitmap** [comment]
You are importing the ECMAScript module version, which will throw an error because IE11 doesn't support ES modules. 

The root file in the `dist` directory (`./node_modules/react-hook-inview/dist/index.js`) is the legacy ES5 build.

**Comment by uxigene** [comment]
Thanks for the reply. Probably this issue can be closed.
